[workspace]
members = [
    "core",
    "wasm",
    "python",
    "tests",
]
resolver = "2"

[workspace.package]
version = "0.1.4"
edition = "2021"
description = "A Rust Library to parse japanese addresses."
repository = "https://github.com/YuukiToriyama/japanese-address-parser"
authors = ["Yuuki Toriyama <github@toriyama.dev>"]
license = "MIT"
keywords = ["parser", "geo", "wasm"]
categories = ["parser-implementations", "wasm"]

[workspace.dependencies]
wasm-bindgen = "0.2.89"
wasm-bindgen-futures = "0.4.39"
wasm-bindgen-test = "0.3.38"
