[package]
name = "japanese-address-parser"
version = "0.1.0"
edition = "2021"
authors = ["Yuuki Toriyama <github@toriyama.dev>"]
repository = "https://github.com/YuukiToriyama/japanese-address-parser"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
async-trait = "0.1.74"
gloo-net = "0.4.0"
nom = "7.1.3"
serde = { version = "1.0.192", features = ["derive"] }
wasm-bindgen = "0.2.88"
wasm-bindgen-test = "0.3.38"
