[workspace]
members = [
    "core",
    "tests"
]
resolver = "2"

[workspace.package]
version = "0.1.0-beta.9"
edition = "2021"
repository = "https://github.com/YuukiToriyama/japanese-address-parser"
authors = ["Yuuki Toriyama <github@toriyama.dev>"]