[package]
name = "japanese-address-parser"
version = "0.1.0"
edition = "2021"
authors = ["Yuuki Toriyama <github@toriyama.dev>"]
repository = "https://github.com/YuukiToriyama/japanese-address-parser"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.7"
gloo-net = "0.4.0"
nom = "7.1.3"
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["full"] }
wasm-bindgen = "0.2.88"
wasm-bindgen-futures = "0.4.38"

[dev-dependencies]
wasm-bindgen-test = "0.3.38"
