[workspace]
members = [
    "core",
    "tests"
]
resolver = "2"

[workspace.package]
version = "0.1.0-beta.9"
edition = "2021"
description = "A Rust Library to parse japanses addresses."
repository = "https://github.com/YuukiToriyama/japanese-address-parser"
authors = ["Yuuki Toriyama <github@toriyama.dev>"]
license = "MIT"
keywords = ["parser", "geo", "wasm"]
categories = ["parser-implementations", "wasm"]
