name: 表記ゆれの報告(町名レベル)
description: 町名の表記ゆれを報告します
title: "表記ゆれの報告: 「」と「」の表記ゆれ"
labels: ["表記ゆれ"]
body:
  - type: markdown
    id: introduction
    attributes:
      value: "町名レベルでの表記ゆれを報告するためのテンプレートです"
  - type: textarea
    id: variety-of-notation
    attributes:
      label: 対応すべき表記ゆれ
      description: 対応すべき表記ゆれを箇条書きで記入してください
      placeholder: "- 東京都千代田区丸ノ内"
    validations:
      required: true
  - type: input
    id: formal-notation
    attributes:
      label: 正式な表記
      description: 町名の正式な表記を https://geolonia.github.io/japanese-addresses/api/ja/都道府県名/市区町村名.json で確認し、記入してください。
      placeholder: "- 東京都千代田区丸の内"
    validations:
      required: true
  - type: textarea
    id: reference
    attributes:
      label: 表記ゆれが確認できる資料/URL
      description: 表記ゆれが確認できる資料についての情報や、ウェブサイトのURLを記載してください。
      placeholder: "行政機関のHPやタウンページの記載など"
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: チェックリスト
      description: Issueを作成する前に以下の項目を確認してください
      options:
        - label: "入力した内容に個人情報が含まれていないことを確認しました。"
          required: true
    validations:
      required: true