name: Unit test & Code check

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          shared-key: 'test-on-pr'
          key: 'main'
          save-if: ${{ github.ref == 'refs/heads/main' }} # mainブランチにコミットが追加された時のみキャッシュを保存する
          cache-provider: 'github'
      - name: Set up clippy
        run: rustup component add clippy
      - name: Code review with clippy
        uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          filter_mode: 'nofilter'
          github_token: ${{ secrets.GITHUB_TOKEN }}
