name: Deploy demo page to GitHub Pages

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Unit Testing for Wasm module
        run: wasm-pack test --firefox --headless
      - name: Build wasm module
        run: wasm-pack build --target web --scope toriyama --features debug
      - name: Move files
        run: |
          mkdir ./publish
          rm ./pkg/.gitignore
          mv ./pkg ./publish
          mv ./public ./publish
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
