name: Deploy demo page to GitHub Pages

on:
  push:
    branches: ["main", "feature/cargo-workspace/*" ] # 動作確認用

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Unit Testing for Wasm module
        working-directory: wasm
        run: wasm-pack test --firefox --headless
      - name: Build wasm module
        working-directory: wasm
        run: wasm-pack build --target web --scope toriyama --out-name japanese_address_parser --features debug
      - name: Move files
        run: |
          mkdir ./publish
          rm ./wasm/pkg/.gitignore
          mv ./wasm/pkg ./publish
          mv ./public ./publish
      # 動作確認用に生成物をアップロードしている
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ghpages-publish-dir
          path: |
            publish
      - name: Deploy to GitHub Pages
        if: ${{ false }} # 動作確認用
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
