name: Python module build check

on:
  pull_request:
    paths-ignore: [ '*.md' ]
  push:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          shared-key: 'maturin-linux'
          key: 'main'
          save-if: ${{ github.ref == 'refs/heads/main' }} # mainブランチにコミットが追加された時のみキャッシュを保存する
          cache-provider: 'github'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          maturin-version: 1.8.1
          target: x86_64
          args: --release --out dist --zig
          working-directory: python
          manylinux: auto

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          shared-key: 'maturin-windows'
          key: 'main'
          save-if: ${{ github.ref == 'refs/heads/main' }} # mainブランチにコミットが追加された時のみキャッシュを保存する
          cache-provider: 'github'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: x64
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          maturin-version: 1.8.1
          target: x64
          args: --release --out dist
          working-directory: python

  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          shared-key: 'maturin-macos'
          key: 'main'
          save-if: ${{ github.ref == 'refs/heads/main' }} # mainブランチにコミットが追加された時のみキャッシュを保存する
          cache-provider: 'github'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          maturin-version: 1.8.1
          target: aarch64
          args: --release --out dist
          working-directory: python

  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          shared-key: 'maturin-sdist'
          key: 'main'
          save-if: ${{ github.ref == 'refs/heads/main' }} # mainブランチにコミットが追加された時のみキャッシュを保存する
          cache-provider: 'github'
      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          maturin-version: 1.8.1
          command: sdist
          args: --out dist
          working-directory: python
