name: Unit test & Integration test

on:
  pull_request:
    paths-ignore: [ '*.md' ]
  push:
    branches: [ 'main' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          shared-key: 'test-on-pr'
          key: 'main'
          save-if: ${{ github.ref == 'refs/heads/main' }} # mainブランチにコミットが追加された時のみキャッシュを保存する
      - name: Test core
        working-directory: core
        run: |
          cargo test
          cargo test --features=blocking
          cargo test --features=experimental
      - name: Integration test
        working-directory: tests
        run: cargo test

  run-tests-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          shared-key: 'wasm-pack'
          key: 'main'
          save-if: ${{ github.ref == 'refs/heads/main' }} # mainブランチにコミットが追加された時のみキャッシュを保存する
          cache-provider: 'github'
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Run wasm-pack test for core(japanese-address-parser)
        working-directory: core
        run: wasm-pack test --firefox --headless
      - name: Build check for wasm crate
        working-directory: wasm
        run: wasm-pack build --target web --scope toriyama

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install minimum supported version
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.75.0
      - name: Basic build
        run: |
          # `litemap`と`zerofrom`の最新版でMSRVがv1.81.0になってしまっていて、Rust1.75.0でビルドしようとすると失敗するため以下を実行
          # `litemap`と`zerofrom`においてMSRVが元に戻ったり、`japanese-address-parser`自体のMSRVが1.81.0以上になったら以下の処理は不要になるので除却する
          cargo update litemap --precise 0.7.4
          cargo update zerofrom --precise 0.1.5
          cargo build --verbose
      - name: Build docs
        run: |
          # `litemap`と`zerofrom`の最新版でMSRVがv1.81.0になってしまっていて、Rust1.75.0でビルドしようとすると失敗するため以下を実行
          # `litemap`と`zerofrom`においてMSRVが元に戻ったり、`japanese-address-parser`自体のMSRVが1.81.0以上になったら以下の処理は不要になるので除却する
          cargo update litemap --precise 0.7.4
          cargo update zerofrom --precise 0.1.5
          cargo doc --verbose
