name: Unit test & Code format check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build check
      run: cargo build --verbose
    - name: Unit Testing
      run: cargo test --verbose
    - name: Code style check
      run: cargo fmt --check
