name: Unit test & Code format check

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up clippy
        run: rustup component add clippy
      - name: Code review with clippy
        uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          filter_mode: 'nofilter'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build check
        run: cargo build --verbose
      - name: Unit Testing
        run: cargo test --verbose
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build wasm module
        run: cd core && wasm-pack build --target web --scope toriyama # coreモジュールを作成したことで以下のステップの実行がこけるようになったため追加。あとで整理する。
      - name: Unit Testing for Wasm module
        run: wasm-pack test --firefox --headless
