name: (Survey)Python module build check

on:
  pull_request:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: armv7
          args: --release --out dist --zig
          working-directory: python
          sccache: 'true'
          manylinux: auto