name: (Survey)Python module build check

on:
  pull_request:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64
          - x86
          - aarch64
          - armv7
          - s390x
          - ppc64le
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Zig
        run: python3 -m pip install ziglang==0.11.0
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --zig
          working-directory: python
          sccache: 'true'
          manylinux: auto