name: Upload artifact to crates.io

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: crates-io
    permissions:
      id-token: write # Required for OIDC token exchange
    defaults:
      run:
        working-directory: core
    steps:
      - uses: actions/checkout@v4
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Build check
        run: cargo build --verbose
      - name: Unit Testing
        run: |
          cargo test
          cargo test --features blocking

      - name: Try packaging
        run: cargo publish --dry-run
      - name: Show files will be included
        run: cargo package --list
      - name: Upload artifact to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}