name: wasm-pack build & wasm-pack test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  wasm-pack:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wasm
    steps:
      - uses: actions/checkout@v4
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build wasm module
        run: wasm-pack build --target web --scope toriyama
      - name: Unit Testing for Wasm module
        run: wasm-pack test --firefox --headless
