name: wasm-pack build & wasm-pack test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  wasm-pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          save-if: ${{ github.ref == 'refs/heads/main' }} # mainブランチにコミットが追加された時のみキャッシュを保存する
          cache-provider: 'github'
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Unit test for core module
        working-directory: core
        run: wasm-pack test --firefox --headless
      - name: Build test for wasm module
        working-directory: wasm
        run: wasm-pack build --target web --scope toriyama
